repuestos/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [    
    #path('accounts/', include('registration.backends.default.urls')),
    path('', include('vistaprevia.urls')),  
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),
    path('usuarios/', include('usuarios.urls')),    
     
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

tienda/urls.py
from django.urls import path
from tienda import views
from tienda.views import VerImagenes

urlpatterns = [
  path('cargar/', views.cargar_imagen, name="cargar"),
  path('<int:producto_id>/ver/', views.ver_imagen, name="ver"),
  path('verimagenes/', VerImagenes.as_view(), name="verimagenes"),
]

productos/models.py
from django.db import models
from django.utils.html import format_html
import datetime

class Categoria(models.Model):
    nombre = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return '%s' % self.nombre



class Producto(models.Model):
    Oferta = "Oferta"
    Publicado = "Publicado"
    Vendido = "Vendido"
    En_falta= "En Falta"
    
    
    APROBACION_PRODUCTO = (
      (Oferta, "Oferta"),
      (Publicado, "Publicado"),
      (Vendido ,"Vendido"),
      (En_falta,"En Falta")
    )
    estado = models.CharField(max_length=10, choices=APROBACION_PRODUCTO, default="Publicado")
    producto = models.CharField(max_length=200)
    fecha_publicacion = models.DateTimeField('Fecha de publicación')
    imagen = models.ImageField(upload_to="producto/%Y/%m/%d", blank=True, null=True)    
    #categoria = models.ManyToManyField(Categoria)
    categoria = models.ForeignKey(Categoria, blank=False, null=True, on_delete=models.CASCADE
    )

    stock = models.IntegerField(default=0)
    descripcion = models.TextField(  default="")
    precio = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    descuento = models.IntegerField(default=0)


    def tipo_de_producto(self):
      if self.estado == "Vendido":
        return format_html('<span style="background-color: #258a60;color:#ffffff;padding: 7px;">{}</span>', self.estado, )
      elif self.estado == "Oferta":
        return format_html('<span style="background-color: #f80174;color:#ffffff; padding: 7px;">{}</span>', self.estado, )
      elif self.estado == "Publicado":
        return format_html('<span style="background-color: #3520F7;color:#ffffff;padding: 7px;">{}</span>', self.estado, )
      elif self.estado == "En Falta":
        return format_html('<span style="background-color: #FA150C;color:#ffffff;padding: 7px;">{}</span>', self.estado, )
     
    def __str__(self, ):
      return self.producto  + "------" + str(self.fecha_publicacion)

tienda/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
import time


class Datosusuario(models.Model):
  usuario          = models.OneToOneField(User, blank=False, null=True,on_delete=models.CASCADE,)
  imagen           = models.ImageField(upload_to="producto/%y/%m/%d", default='defecto/defecto.png',blank=True, null=True)
  nombre           = models.CharField(max_length=50)
  apellido         = models.CharField(max_length=50)
  fecha_nacimiento = models.DateField(blank=True, null=True)
  pais             = models.CharField(max_length=30, blank=True)
  provincia        = models.CharField(max_length=40, blank=True)
  ciudad           = models.CharField(max_length=40, blank=True)
  domicilio        = models.CharField(max_length=80, blank=True)
  codigo_postal    = models.CharField(max_length=50, blank=True)
  telefono         = models.CharField(max_length=30, blank=True)
  celular          = models.CharField(max_length=30, blank=True)
  documento        = models.CharField(max_length=30, blank=True)
  cuit             = models.CharField(max_length=30, blank=True)
  

  def __str__(self):
    return self.usuario.username
  

tienda/forms.py
from django.forms import ModelForm
from productos.models import Producto

class CargarForm(ModelForm):
  class Meta:
    model=Producto
    fields= ['producto', 'fecha_publicacion', 'imagen',]

  def __init__(self, *args, **kwargs):
      super(CargarForm, self).__init__( *args, **kwargs)

tienda/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from productos.models import Producto
from tienda.forms import CargarForm
from django.http import Http404
from django.views.generic import View
from django.db.models import Q



def cargar_imagen(request):
  params={}
  
  if request.method == 'POST':
    form = CargarForm(request.POST, request.FILES)
    params['form']=form
    if form.is_valid():
      producto=form.cleaned_data['producto']
      fecha_publicacion=form.cleaned_data['fecha_publicacion']
      imagen=form.cleaned_data['imagen']

      nuevo_producto = Producto(producto=producto, fecha_publicacion=fecha_publicacion, imagen=imagen)
      nuevo_producto.save()
      return redirect('index')
  else:
    form = CargarForm()
    params['form']=form
    return render(request, 'tienda/formulario.html', params)

class VerImagenes(View):
  template = "tienda/verimagenes.html"
  def get(self, request):
    params={}
    try:
      productos = Producto.objects.all()
    except Producto.DoesNotExist:
      raise Http404
    params["productos"] = productos  

    return render(request, self.template, params)

  def post(self, request):
        parans={}
        producto=request.POST.get("producto")
        el_pedido = request.session.get("el_pedido")
        if el_pedido:
            cantidad = el_pedido.get(producto)
            if cantidad:
                el_pedido[producto]=cantidad+1
            else:
                el_pedido[producto]=1
        else:
            el_pedido={}
            el_pedido[producto]=1

        request.session["el_pedido"] = el_pedido
        print(request.session["el_pedido"])


        return redirect("verimagenes")

def ver_imagen(request, producto_id):
      params={}
      try:
        producto = Producto.objects.get(pk=producto_id)
      except Producto.DoesNotExist:
        raise Http404
      params["producto"] = producto
      return render(request, "tienda/verimagen.html", params)

templates/tienda/formulario.html
{% extends "layout.html" %}
{% load static %}
{% block tienda %}
 
<section class="container-fluid">
  <div class="row">
      <div class="col-12" style="padding:0px;  ">
         <br/> 
      </div>
  </div>
</section>
 <div class="container">
  <div class="row ">
    <div class="col-12">
      <h1>Mi tienda</h1>
    </div>
    <div class="col-12 col-sm-10 col-md-8 col-lg-6">
      <form id="form_cargar" action="/tienda/cargar/" method="post" enctype="multipart/form-data">{% csrf_token %}        
          <label for="id_producto">Producto</label>             
            <input type="text" name="producto" maxlength="200" required=""  id="id_producto">
          <label for="id_fecha_publicacion">Fecha de publicación</label>             
            <input type="date" name="fecha_publicacion" required="" id="id_fecha_publicacion">
          <label for="id_imagen">Imagen</label>   
            <input type="file" name="imagen" accept="image/*" id="id_imagen">
            <input class="btn btn-dark btn-sm" type="submit" value="Submit">
      </form>
    </div>
  </div>
 </div>


{% endblock %}   
{% block scripts %} 
   <script src="{% static 'js/jqerry.js' %}"></script>
   <script>
    $("#id_fecha_publicacion").datepicker({
      inline: true
    });
   </script>
{% endblock %}
   

   

templates/tienda/verimagen.html
{% extends "layout.html" %}
{% load static %}
{% block tienda %}

<div class="container" style="margin-top: 90px; text-align: center;   
padding: 20px;color: rgb(2, 43, 2);">
  <h1>El id de la imagen es: {{producto.id}}</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
 
  <div class="col-12 col-md-4 mb-6">
    
    <div class="card h-100 border-0">
      <img src="/media/{{producto.imagen}}" class="card-img-top" alt="moto en velocidad" height="300px">
      <div class="card-body">
        <h5 class="card-title">{{producto.estado}}</h5>  
        <p class="card-text">{{producto.producto}}</p>
      <p class="card-text">{{producto.descripcion}}</p>
      <p class="card-text">${{producto.precio}}</p>       
      <a href="{% url 'verimagenes' %}" class="btn btn-dark btn-sm">Volver</a>
      </div>
    </div>
  </div>
 
{% endblock %}   

templates/tienda/verimagenes.html
{% extends "layout.html" %}
{% load static %}
{% load mi_tienda %}

{% block tienda %}


<div class="titulo ">
  <h1 class="texto">Tienda de Productos</h1>
</div>
<article>
  <div class="row justify-content-center">
    {% for producto in productos %}
    <div class="col-12 col-md-4 ">
      <div class="card h-100 border-0">
        <img src="/media/{{producto.imagen}}" class="card-img-top" alt="moto en velocidad">
        <div class="card-body">
          <h5 class="card-title">{{producto.producto}}</h5>
          <p class="card-text">{{producto.descripcion|slice:":95"}}</p>
          <p class="card-text">${{producto.precio}}</p>
          {% if request.session.el_pedido %}
          <span>{{producto|en_pedido:request.session.el_pedido}}</span>
          {% endif %}
          <hr />
          <!--Boton para agregar producto-->
          <form action="{% url 'verimagenes' %}" method="post" style="border:none">{% csrf_token %}
            <input hidden type="text" name="producto" value="{{producto.id}}" />
            <input type="submit" class="btn btn-dark btn-sm" value="Agregar" />
          </form>



          <a href="{% url 'ver' producto.id %}" class="btn btn-dark btn-sm">Ver</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</article>



{% endblock %}